name: ServiceNow GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  publish_SD:
    name: publish test apps to app repo
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Publish App
        id: publish_app1
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.5
          versionFormat: template
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowSourceInstance: ${{ secrets.CHIARNGDEV }}
          appSysID: ${{ secrets.APPQUEUE1 }}
          
      - name: ServiceNow CI/CD Publish App
        id: publish_app2
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.5
          versionFormat: template
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowSourceInstance: ${{ secrets.CHIARNGDEV }}
          appSysID: ${{ secrets.APPQUEUE2 }}

      - name: ServiceNow CI/CD Publish App
        id: publish_app3
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.5
          versionFormat: template
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowSourceInstance: ${{ secrets.CHIARNGDEV }}
          appSysID: ${{ secrets.APPQUEUE3 }}

    outputs:
      publishversion: ${{ steps.publish_app1.outputs.newVersion }}

  install_SD:
    name: Install test apps on SD
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Install App
        id: install_app1
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.publish_SD.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.CHIARNGTEST }}
          appSysID: ${{ secrets.APPQUEUE1 }}

      - name: ServiceNow CI/CD Install App
        id: install_app2
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.publish_SD.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.CHIARNGTEST }}
          appSysID: ${{ secrets.APPQUEUE2 }}
          
      - name: ServiceNow CI/CD Install App
        id: install_app3
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.publish_SD.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.CHIARNGTEST }}
          appSysID: ${{ secrets.APPQUEUE3 }}

    outputs:
      publishversion: ${{ needs.install_SD.outputs.publishversion }}

  install_T:
    name: Install test apps on T
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Install App
        id: install_app1
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.install_SD.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.CHIARNGNIGHTLY }}
          appSysID: ${{ secrets.APPQUEUE1 }}

      - name: ServiceNow CI/CD Install App
        id: install_app2
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.install_SD.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.CHIARNGNIGHTLY }}
          appSysID: ${{ secrets.APPQUEUE2 }}
          
      - name: ServiceNow CI/CD Install App
        id: install_app3
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.install_SD.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.CHIARNGNIGHTLY }}
          appSysID: ${{ secrets.APPQUEUE3 }}
