name: ServiceNow GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  install_bunch_of_things:
    name: Install bunch of things
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Install App
        id: install_app1
        uses: ServiceNow/sncicd-install-app@2.0.0
        env:
          snowUsername: ${{ secrets.SN_USERNAME }}
          snowPassword: ${{ secrets.SN_PASSWORD }}
          snowInstallInstance: ${{ secrets.SN_TEST_INSTANCE }}
          appSysID: ${{ secrets.SN_APP_SYSID }}

      - name: ServiceNow CI/CD Install App
        id: install_app2
        uses: ServiceNow/sncicd-install-app@2.0.0
        env:
          snowUsername: ${{ secrets.SN_USERNAME }}
          snowPassword: ${{ secrets.SN_PASSWORD }}
          snowInstallInstance: ${{ secrets.SN_TEST_INSTANCE }}
          appSysID: ${{ secrets.SN_APP_SYSID }}
          
      - name: ServiceNow CI/CD Install App
        id: install_app3
        uses: ServiceNow/sncicd-install-app@2.0.0
        env:
          snowUsername: ${{ secrets.SN_USERNAME }}
          snowPassword: ${{ secrets.SN_PASSWORD }}
          snowInstallInstance: ${{ secrets.SN_TEST_INSTANCE }}
          appSysID: ${{ secrets.SN_APP_SYSID }}
