name: ServiceNow GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  publish_SD:
    name: publish test apps to app repo
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Publish App
        id: publish_app1
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.0
          versionFormat: template
        env:
          snowUsername: ${{ secrets.NOW_USERNAME }}
          snowPassword: ${{ secrets.NOW_PASSWORD }}
          snowSourceInstance: ${{ secrets.CHIARNGDEV }}
          appScope: ${{ secrets.APPQUEUE1 }}
          
      - name: ServiceNow CI/CD Publish App
        id: publish_app2
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.0
          versionFormat: template
        env:
          snowUsername: ${{ secrets.NOW_USERNAME }}
          snowPassword: ${{ secrets.NOW_PASSWORD }}
          snowSourceInstance: ${{ secrets.CHIARNGDEV }}
          appScope: ${{ secrets.APPQUEUE2 }}

      - name: ServiceNow CI/CD Publish App
        id: publish_app3
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.0
          versionFormat: template
        env:
          snowUsername: ${{ secrets.NOW_USERNAME }}
          snowPassword: ${{ secrets.NOW_PASSWORD }}
          snowSourceInstance: ${{ secrets.CHIARNGDEV }}
          appScope: ${{ secrets.APPQUEUE3 }}

    outputs:
      publishversion: ${{ steps.publish_app.outputs.newVersion }}

  install_SD:
    name: Install test apps on SD
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Install App
        id: install_app1
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{steps.publish_app.outputs.newVersion}}
        env:
          snowUsername: ${{ secrets.NOW_USERNAME }}
          snowPassword: ${{ secrets.NOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.CHIARNGTEST }}
          appScope: ${{ secrets.APPQUEUE1 }}

      - name: ServiceNow CI/CD Install App
        id: install_app2
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{steps.publish_app.outputs.newVersion}}
        env:
          snowUsername: ${{ secrets.NOW_USERNAME }}
          snowPassword: ${{ secrets.NOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.CHIARNGTEST }}
          appScope: ${{ secrets.APPQUEUE2 }}
          
      - name: ServiceNow CI/CD Install App
        id: install_app3
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{steps.publish_app.outputs.newVersion}}
        env:
          snowUsername: ${{ secrets.NOW_USERNAME }}
          snowPassword: ${{ secrets.NOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.CHIARNGTEST }}
          appScope: ${{ secrets.APPQUEUE3 }}

    outputs:
      publishversion: ${{ needs.build.outputs.publishversion }}

  install_T:
    name: Install test apps on T
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Install App
        id: install_app1
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{steps.publish_app.outputs.newVersion}}
        env:
          snowUsername: ${{ secrets.NOW_USERNAME }}
          snowPassword: ${{ secrets.NOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.CHIARNGNIGHTLY }}
          appScope: ${{ secrets.APPQUEUE1 }}

      - name: ServiceNow CI/CD Install App
        id: install_app2
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{steps.publish_app.outputs.newVersion}}
        env:
          snowUsername: ${{ secrets.NOW_USERNAME }}
          snowPassword: ${{ secrets.NOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.CHIARNGNIGHTLY }}
          appScope: ${{ secrets.APPQUEUE2 }}
          
      - name: ServiceNow CI/CD Install App
        id: install_app3
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{steps.publish_app.outputs.newVersion}}
        env:
          snowUsername: ${{ secrets.NOW_USERNAME }}
          snowPassword: ${{ secrets.NOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.CHIARNGNIGHTLY }}
          appScope: ${{ secrets.APPQUEUE3 }}
