name: ServiceNow GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish test apps to app repo
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Publish App
        id: publish_app1
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.5
          versionFormat: template
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowSourceInstance: ${{ secrets.CHIARNGDEV }}
          appSysID: ${{ secrets.APPQUEUE1 }}
          
      - name: ServiceNow CI/CD Publish App
        id: publish_app2
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.5
          versionFormat: template
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowSourceInstance: ${{ secrets.CHIARNGDEV }}
          appSysID: ${{ secrets.APPQUEUE2 }}

      - name: ServiceNow CI/CD Publish App
        id: publish_app3
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.5
          versionFormat: template
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowSourceInstance: ${{ secrets.CHIARNGDEV }}
          appSysID: ${{ secrets.APPQUEUE3 }}

    outputs:
      publishversion: ${{ steps.publish_app1.outputs.newVersion }}

  install_app1_SanDiego:
    name: Install app1 on SD instance
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow CI/CD Install App
        id: install_app1_SanDiego
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.publish.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.CHIARNGTEST }}
          appSysID: ${{ secrets.APPQUEUE1 }}
  
  install_app1_Tokyo:
    name: Install app1 on T instance
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow CI/CD Install App
        id: install_app1_Tokyo
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.publish.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD2 }}
          nowInstallInstance: ${{ secrets.CHIARNGNIGHTLY }}
          appSysID: ${{ secrets.APPQUEUE1 }}

  install_app2_SanDiego:
    name: Install app2 on SD instance
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow CI/CD Install App
        id: install_app1_SanDiego
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.publish.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.CHIARNGTEST }}
          appSysID: ${{ secrets.APPQUEUE2 }}
  
  install_app2_Tokyo:
    name: Install app2 on T instance
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow CI/CD Install App
        id: install_app1_Tokyo
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.publish.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD2 }}
          nowInstallInstance: ${{ secrets.CHIARNGNIGHTLY }}
          appSysID: ${{ secrets.APPQUEUE2 }}
          
  install_app3_SanDiego:
    name: Install app3 on SD instance
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow CI/CD Install App
        id: install_app1_SanDiego
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.publish.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.CHIARNGTEST }}
          appSysID: ${{ secrets.APPQUEUE3 }}
  
  install_app3_Tokyo:
    name: Install app3 on T instance
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow CI/CD Install App
        id: install_app1_Tokyo
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.publish.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD2 }}
          nowInstallInstance: ${{ secrets.CHIARNGNIGHTLY }}
          appSysID: ${{ secrets.APPQUEUE3 }}

# trigger demo
# last try
# demo trigger again
# demo
